<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CustomLogger" Version="1.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RS3PriceChecker.Models\RS3PriceChecker.Models.csproj" />
    <ProjectReference Include="..\RS3PriceChecker.Repository\RS3PriceChecker.Repository.csproj" />
  </ItemGroup>

</Project>
